using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Common.Dynamic;

namespace Apps.Hubspot.DataSourceHandlers
{
    public class LanguageHandler : IStaticDataSourceItemHandler
    {
        private static Dictionary<string, string> EnumValues => new()
        {
            { "af", "Afrikaans" },
            { "ar", "Arabic" },
            { "ar-ae", "Arabic (United Arab Emirates)" },
            { "ar-bh", "Arabic (Bahrain)" },
            { "ar-dz", "Arabic (Algeria)" },
            { "ar-eg", "Arabic (Egypt)" },
            { "ar-iq", "Arabic (Iraq)" },
            { "ar-jo", "Arabic (Jordan)" },
            { "ar-kw", "Arabic (Kuwait)" },
            { "ar-lb", "Arabic (Lebanon)" },
            { "ar-ly", "Arabic (Libya)" },
            { "ar-ma", "Arabic (Morocco)" },
            { "ar-om", "Arabic (Oman)" },
            { "ar-qa", "Arabic (Qatar)" },
            { "ar-sa", "Arabic (Saudi Arabia)" },
            { "ar-sd", "Arabic (Sudan)" },
            { "ar-sy", "Arabic (Syria)" },
            { "ar-tn", "Arabic (Tunisia)" },
            { "ar-ye", "Arabic (Yemen)" },
            { "as", "Assamese" },
            { "be", "Belarusian" },
            { "be-by", "Belarusian (Belarus)" },
            { "bg", "Bulgarian" },
            { "bg-bg", "Bulgarian (Bulgaria)" },
            { "bn", "Bangla" },
            { "bs", "Bosnian" },
            { "ca", "Catalan" },
            { "ca-es", "Catalan (Spain)" },
            { "cs", "Czech" },
            { "cs-cz", "Czech (Czechia)" },
            { "da", "Danish" },
            { "da-dk", "Danish (Denmark)" },
            { "de", "German" },
            { "de-at", "German (Austria)" },
            { "de-ch", "German (Switzerland)" },
            { "de-de", "German (Germany)" },
            { "de-gr", "German (Greece)" },
            { "de-li", "German (Liechtenstein)" },
            { "de-lu", "German (Luxembourg)" },
            { "el", "Greek" },
            { "el-cy", "Greek (Cyprus)" },
            { "el-gr", "Greek (Greece)" },
            { "en", "English" },
            { "en-ae", "English (United Arab Emirates)" },
            { "en-au", "English (Australia)" },
            { "en-be", "English (Belgium)" },
            { "en-ca", "English (Canada)" },
            { "en-ch", "English (Switzerland)" },
            { "en-cn", "English (China)" },
            { "en-de", "English (Germany)" },
            { "en-ee", "English (Estonia)" },
            { "en-gb", "English (United Kingdom)" },
            { "en-hk", "English (Hong Kong SAR China)" },
            { "en-ie", "English (Ireland)" },
            { "en-in", "English (India)" },
            { "en-ke", "English (Kenya)" },
            { "en-lu", "English (Luxembourg)" },
            { "en-mt", "English (Malta)" },
            { "en-mx", "English (Mexico)" },
            { "en-my", "English (Malaysia)" },
            { "en-nl", "English (Netherlands)" },
            { "en-nz", "English (New Zealand)" },
            { "en-ph", "English (Philippines)" },
            { "en-pk", "English (Pakistan)" },
            { "en-se", "English (Sweden)" },
            { "en-sg", "English (Singapore)" },
            { "en-us", "English (United States)" },
            { "en-za", "English (South Africa)" },
            { "en-zw", "English (Zimbabwe)" },
            { "es", "Spanish" },
            { "es-ar", "Spanish (Argentina)" },
            { "es-bo", "Spanish (Bolivia)" },
            { "es-cl", "Spanish (Chile)" },
            { "es-co", "Spanish (Colombia)" },
            { "es-cr", "Spanish (Costa Rica)" },
            { "es-cu", "Spanish (Cuba)" },
            { "es-do", "Spanish (Dominican Republic)" },
            { "es-ec", "Spanish (Ecuador)" },
            { "es-es", "Spanish (Spain)" },
            { "es-gt", "Spanish (Guatemala)" },
            { "es-hn", "Spanish (Honduras)" },
            { "es-mx", "Spanish (Mexico)" },
            { "es-ni", "Spanish (Nicaragua)" },
            { "es-pa", "Spanish (Panama)" },
            { "es-pe", "Spanish (Peru)" },
            { "es-pr", "Spanish (Puerto Rico)" },
            { "es-py", "Spanish (Paraguay)" },
            { "es-sv", "Spanish (El Salvador)" },
            { "es-us", "Spanish (United States)" },
            { "es-uy", "Spanish (Uruguay)" },
            { "es-ve", "Spanish (Venezuela)" },
            { "et", "Estonian" },
            { "et-ee", "Estonian (Estonia)" },
            { "eu", "Basque" },
            { "fa", "Persian" },
            { "fi", "Finnish" },
            { "fi-fi", "Finnish (Finland)" },
            { "fo", "Faroese" },
            { "fr", "French" },
            { "fr-be", "French (Belgium)" },
            { "fr-ca", "French (Canada)" },
            { "fr-ch", "French (Switzerland)" },
            { "fr-fr", "French (France)" },
            { "fr-lu", "French (Luxembourg)" },
            { "fr-mc", "French (Monaco)" },
            { "fr-tn", "French (Tunisia)" },
            { "gl", "Galician" },
            { "gu", "Gujarati" },
            { "he", "Hebrew" },
            { "hi", "Hindi" },
            { "hi-in", "Hindi (India)" },
            { "hr", "Croatian" },
            { "hr-hr", "Croatian (Croatia)" },
            { "hu", "Hungarian" },
            { "hu-hu", "Hungarian (Hungary)" },
            { "hy", "Armenian" },
            { "id", "Indonesian" },
            { "is", "Icelandic" },
            { "is-is", "Icelandic (Iceland)" },
            { "it", "Italian" },
            { "it-ch", "Italian (Switzerland)" },
            { "it-it", "Italian (Italy)" },
            { "ja", "Japanese" },
            { "ja-jp", "Japanese (Japan)" },
            { "ka", "Georgian" },
            { "kk", "Kazakh" },
            { "kn", "Kannada" },
            { "ko", "Korean" },
            { "ko-kr", "Korean (South Korea)" },
            { "ku", "Kurdish" },
            { "ky", "Kyrgyz" },
            { "lo", "Lao" },
            { "lt", "Lithuanian" },
            { "lt-lt", "Lithuanian (Lithuania)" },
            { "lv", "Latvian" },
            { "lv-lv", "Latvian (Latvia)" },
            { "mk", "Macedonian" },
            { "mk-mk", "Macedonian (North Macedonia)" },
            { "mn", "Mongolian" },
            { "mr", "Marathi" },
            { "ms", "Malay" },
            { "ms-bn", "Malay (Brunei)" },
            { "ms-my", "Malay (Malaysia)" },
            { "my", "Burmese" },
            { "my-mm", "Burmese (Myanmar (Burma))" },
            { "nb", "Norwegian Bokmål" },
            { "nb-no", "Norwegian Bokmål (Norway)" },
            { "ne", "Nepali" },
            { "nl", "Dutch" },
            { "nl-be", "Dutch (Belgium)" },
            { "nl-ch", "Dutch (Switzerland)" },
            { "nl-lu", "Dutch (Luxembourg)" },
            { "nl-nl", "Dutch (Netherlands)" },
            { "no", "Norwegian" },
            { "no-no", "Norwegian (Norway)" },
            { "pa", "Punjabi" },
            { "pa-in", "Punjabi (India)" },
            { "pa-pk", "Punjabi (Pakistan)" },
            { "pl", "Polish" },
            { "pl-pl", "Polish (Poland)" },
            { "pt", "Portuguese" },
            { "pt-br", "Portuguese (Brazil)" },
            { "pt-pt", "Portuguese (Portugal)" },
            { "ro", "Romanian" },
            { "ro-ro", "Romanian (Romania)" },
            { "ru", "Russian" },
            { "ru-ru", "Russian (Russia)" },
            { "si", "Sinhala" },
            { "sk", "Slovak" },
            { "sk-sk", "Slovak (Slovakia)" },
            { "sl", "Slovenian" },
            { "sl-si", "Slovenian (Slovenia)" },
            { "sq", "Albanian" },
            { "sq-al", "Albanian (Albania)" },
            { "sr", "Serbian" },
            { "sr-ba", "Serbian (Bosnia & Herzegovina)" },
            { "sr-cs", "Serbian (Serbia and Montenegro)" },
            { "sr-me", "Serbian (Montenegro)" },
            { "sr-rs", "Serbian (Serbia)" },
            { "sv", "Swedish" },
            { "sv-fi", "Swedish (Finland)" },
            { "sv-se", "Swedish (Sweden)" },
            { "sw", "Swahili" },
            { "ta", "Tamil" },
            { "te", "Telugu" },
            { "th", "Thai" },
            { "th-th", "Thai (Thailand)" },
            { "tl", "Tagalog" },
            { "tr", "Turkish" },
            { "tr-tr", "Turkish (Türkiye)" },
            { "uk", "Ukrainian" },
            { "uk-ua", "Ukrainian (Ukraine)" },
            { "ur", "Urdu" },
            { "uz", "Uzbek" },
            { "vi", "Vietnamese" },
            { "vi-vn", "Vietnamese (Vietnam)" },
            { "zh", "Chinese" },
            { "zh-cn", "Chinese (Simplified, China)" },
            { "zh-hans", "Chinese (Simplified, Hans)" },
            { "zh-hant", "Chinese (Traditional, Hant)" },
            { "zh-hk", "Chinese (Hong Kong SAR China)" },
            { "zh-mo", "Chinese (Macao SAR China)" },
            { "zh-sg", "Chinese (Singapore)" },
            { "zh-tw", "Chinese (Traditional, Taiwan)" },
        };


        IEnumerable<DataSourceItem> IStaticDataSourceItemHandler.GetData()
        {
            return EnumValues.Select(e => new DataSourceItem
            {
                Value = e.Key,
                DisplayName = e.Value
            });
        }
    }
}
